config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  # Users will be met with an assortment of recent articles, questions and interviews.
  root :to => 'homepage#index'


  get '/statics', to: 'statics#index'
  post '/images/remove_image', to: 'images#remove_image'
  
  resources :users
  resources :articles
  resources :questions
  resources :pieces
  resources :images
  resources :comments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true


  def print_errors
    if self.errors.any? 
      puts "Errors: "
      self.errors.full_messages.each do |message| 
        puts message 
      end
    end
  end
end

app/models/article.rb
class Article < ApplicationRecord
  has_one :piece, as: :piece_owner
  accepts_nested_attributes_for :piece, allow_destroy: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :piece
end

app/models/image.rb
class Image < ApplicationRecord

  # Mount Carrier Wave image uploader
  mount_uploader :image, ImageUploader
end

app/models/paragraph.rb
class Paragraph < ApplicationRecord
  belongs_to :piece
end

app/models/piece.rb
class Piece < ApplicationRecord
  belongs_to :piece_owner, polymorphic: true
  
  has_many :comments, dependent: :destroy
  has_many :paragraphs, dependent: :destroy
  has_many :quotes, dependent: :destroy
  has_many :images, as: :image_owner

  accepts_nested_attributes_for :paragraphs, allow_destroy: true
  accepts_nested_attributes_for :quotes, allow_destroy: true
  accepts_nested_attributes_for :images, allow_destroy: true
end

app/models/question.rb
class Question < ApplicationRecord
  has_one :piece, as: :piece_owner
  accepts_nested_attributes_for :piece, allow_destroy: true
end

app/models/quote.rb
class Quote < ApplicationRecord
  belongs_to :piece
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :user_stories, dependent: :destroy
  has_many :questions, dependent: :destroy

end

app/models/user_story.rb
class UserStory < ApplicationRecord
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index

  end

  def show
    @article = Article.find(params[:id])
    @comment = @article.piece.comments.build
  end

  def new
    @article = Article.new
    @article.piece = Piece.new
  end

  def create
    @article = Article.new
    # TODO: The following is a very hacky solution. Come back and fix it.
    if @article.save
      @piece = @article.build_piece(article_params[:piece_attributes])
      if @piece.save
        redirect_to @article
      else
        render 'new'
      end
    else
      render 'new'
    end
  end

  def edit
    @article = Article.find(params[:id])
  end


  def update
    @article = Article.find(params[:id])
 
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end 

  private

    def article_params
      params.require(:article).permit(piece_attributes: [:id, :title, :body])
    end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def create
    @new_image = Image.new
    @new_image.image = image_params[0]
    if @new_image.save 
      @uploaded_file = {files: [{url: root_url + @new_image.image.url}]}
      render json: @uploaded_file
    else
      @new_image.print_errors  
    end
  end

  def destroy
    puts "============================"
    puts params.inspect
  end

  def remove_image
    puts "============================"
    id = params[:file].split('/')[-2]
    image_to_remove = Image.find(id)
    image_to_remove.remove_image!
    if image_to_remove.destroy
      puts "destroyed "
    end

  end

  private 

    def image_params
      params.require(:files)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/pieces_helper.rb
module PiecesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/helpers/user_stories_helper.rb
module UserStoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/edit.html.erb
<div class="row">

  <div class="col-md-3">
  
</div>
<div class="col-md-6">
  <%= form_with model: @article, class: "form-group" do |form| %>
    Piece:
    <%= form.fields_for :piece do |piece_form| %>
      <div class="field">
        <%= piece_form.text_field :title, class: "form-control" %>
      </div>
      <br>
      <div class="field">
        <%= piece_form.text_area :body, class: "editable form-control" %>
      </div>
     
      
    <% end %>
    <%= form.submit %>
  <% end %>
 
</div>
<div class="col-md-3">
  
</div>
  
</div>



<script type="text/javascript">
  var editor = new MediumEditor('.editable');

  $(function () {
    $('.editable').mediumInsert({
      editor: editor,
      addons: {
        images: {
          fileUploadOptions: {
            url: '<%= images_path %>',
            acceptFileTypes: new RegExp('(\.|\/)(gif|jpe?g|png)$')
          },

          fileDeleteOptions: {
            url: '<%= images_path %>/remove_image'
          }
        }
      }

    });
  });



</script>

app/views/articles/new.html.erb
<div class="row">

  <div class="col-md-3">
  
</div>
<div class="col-md-6">
  <%= form_with model: @article, class: "form-group" do |form| %>
    Piece:
    <%= form.fields_for :piece do |piece_form| %>
      <div class="field">
        <%= piece_form.text_field :title, class: "form-control" %>
      </div>
      <br>
      <div class="field">
        <%= piece_form.text_area :body, class: "editable form-control" %>
      </div>
     
      
    <% end %>
    <%= form.submit %>
  <% end %>
 
</div>
<div class="col-md-3">
  
</div>
  
</div>



<script type="text/javascript">
  var editor = new MediumEditor('.editable');

  $(function () {
    $('.editable').mediumInsert({
      editor: editor,
      addons: {
        images: {
          fileUploadOptions: {
            url: '<%= images_path %>',
            acceptFileTypes: new RegExp('(\.|\/)(gif|jpe?g|png)$')
          },

          fileDeleteOptions: {
            url: '<%= images_path %>/remove_image'
          }
        }
      }

    });
  });



</script>

app/views/articles/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-2">
    </div>
    <div class="col-md-8">
      <div class="piece-container">
        <h2> <%= @article.piece.title%> </h2>
       
          <p>
            <%= @article.piece.body.html_safe %>
          </p>
      </div>

      <div class="comment-container">
        <%= render partial: "comments/comment_form"%>
      </div>
    </div>
    <div class="col-md-2">
    </div>
  </div>
</div>